apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
  annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "256m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
      {{#each azure_access_inbound}}
          - application: {{this.application}}
            namespace: {{this.namespace}}
            cluster: {{this.cluster}}
      {{/each}}
    outbound:
      external:
      {{#each outbound-access-hosts}}
          - host: {{this}}
      {{/each}}
      rules:
      {{#each outbound-access-apps}}
          - application: {{this}}
      {{/each}}
  kafka:
    pool: {{ kafka.pool }}
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 40
    timeout: 10
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 60
    timeout: 10
  prometheus:
    enabled: true
    path: /actuator/prometheus
  gcp:
    buckets:
      - name: {{ bucket_name }}
    sqlInstances:
      - name: {{ database.dbname }}
        type: POSTGRES_14
        diskAutoresize: {{ database.autoResize }}
        tier: {{ database.tier }}
        databases:
          - name: bidrag-dokument-forsendelse
            envVarPrefix: DB
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 1024Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
     - name: BUCKET_NAME
       value: {{ bucket_name }}
  envFrom:
      - secret: bidrag-dokument-forsendelse-encryption-key

