name: bidrag-dokument-forsendelse
ingresses:
  - https://bidrag-dokument-forsendelse.intern.nav.no
env:
  BIDRAG_PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  BIDRAG_PERSON_SCOPE: prod-fss.bidrag.bidrag-person
database:
  dbname: bidrag-dokument-forsendelse
  autoResize: false
  tier: db-custom-1-3840