name: bidrag-dokument-forsendelse
ingresses:
  - https://bidrag-dokument-forsendelse.intern.nav.no
env:
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.prod-fss-pub.nais.io/bidrag-organisasjon
  BIDRAG_ORGANISASJON_SCOPE: prod-fss.bidrag.bidrag-organisasjon

  BIDRAG_DOKUMENT_BESTILLING_URL: https://bidrag-dokument-bestilling.intern.nav.no
  BIDRAG_DOKUMENT_BESTILLING_SCOPE: prod-gcp.bidrag.bidrag-dokument-bestilling

  BIDRAG_DOKUMENT_URL: https://bidrag-dokument.prod-fss-pub.nais.io/bidrag-dokument
  BIDRAG_DOKUMENT_SCOPE: prod-fss.bidrag.bidrag-dokument

  SAK_URL: https://bidrag-sak.prod-fss-pub.nais.io/bidrag-sak
  SAK_SCOPE: prod-fss.bidrag.bidrag-sak
database:
  dbname: bidrag-dokument-forsendelse
  autoResize: false
  tier: db-custom-1-3840
kafka:
  pool: nav-prod
azure_access_inbound:
  - application: bisys
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-dokument
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss