CREATE TABLE IF NOT EXISTS forsendelse
(
    forsendelse_id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1000000000 MINVALUE 1000000000),
    forsendelse_type        text not null,
    arkiv_journalpost_id    text,
    enhet                   text,
    saksnummer              text,
    gjelder_ident           text not null,
    opprettet_av_ident      text,
    opprettet_av_navn       text,
    opprettet_tidspunkt     timestamp without time zone DEFAULT now() NOT NULL,
    endret_tidspunkt        timestamp without time zone DEFAULT now() NOT NULL,
    mottaker_id             integer,
    CONSTRAINT fk_mottaker_id FOREIGN KEY (mottaker_id)
        REFERENCES mottaker(id) MATCH SIMPLE
);

CREATE INDEX idx_fors_saksnummer ON forsendelse(saksnummer);

CREATE TRIGGER update_forsendelse_endret BEFORE UPDATE ON forsendelse FOR EACH ROW EXECUTE PROCEDURE oppdater_endret_tidspunkt();
