CREATE TABLE IF NOT EXISTS mottaker
(
    id                  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    ident               text,
    ident_type          text,
    navn                text,
    språk               text,
    opprettet_tidspunkt timestamp without time zone DEFAULT now() NOT NULL,
    adresse_id          integer,
    CONSTRAINT fk_mottaker_adresse FOREIGN KEY (adresse_id)
        REFERENCES adresse (id) MATCH SIMPLE
);