CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TABLE IF NOT EXISTS dokument
(
    dokument_id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 100000000 MINVALUE 100000000),
    dokumentreferanse_original text,
    journalpost_id_original    text,
    dokumentreferanse_fagarkiv text,
    språk                      text,
    tittel                     text                                      not null,
    dokumentmal_id             text,
    arkivsystem                text,
    dokument_status            text,
    rekkefølge_indeks          int                                       not null,
    metadata                   hstore,
    slettet_tidspunkt          timestamp without time zone,
    opprettet_tidspunkt        timestamp without time zone DEFAULT now() NOT NULL,
    forsendelse_id             bigint                                    not null,
    UNIQUE (journalpost_id_original, dokumentreferanse_original, forsendelse_id),
    CONSTRAINT fk_forsendelse_id FOREIGN KEY (forsendelse_id) REFERENCES forsendelse (forsendelse_id)
);
comment on column dokument.språk is 'Språket på inneholdet i dokumentet. Hvis språket ikke er satt så er inneholdet på samme språk som forsendelse.språk';
comment on column dokument.dokumentreferanse_fagarkiv is 'Referansen til dokumentet i fagarkivet. Dette settes etter forsendelsen er ferdigstilt og arkivert i fagarkivet. Brukes i kombinasjon med forsendelse.journalpost_id_fagarkiv.';

CREATE INDEX idx_dokumentreferanse_fagarkiv ON dokument (dokumentreferanse_fagarkiv);
CREATE INDEX idx_dokumentreferanse_original ON dokument (dokumentreferanse_original);
CREATE INDEX idx_dokument_arkivsystem ON dokument (arkivsystem);
CREATE INDEX idx_dokument_status ON dokument (dokument_status);

create rule beskytt_rad_som_ikke_har_dokumentreferanse_original as
    on delete to dokument
    where dokumentreferanse_original is null
    do instead nothing;