CREATE TABLE IF NOT EXISTS behandling_info
(
    id                  bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    behandling_id       text,
    vedtak_id           text,
    opprettet_tidspunkt timestamp without time zone DEFAULT now() NOT NULL
);