CREATE TABLE IF NOT EXISTS ettersendingsoppgave
(
    id                               bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    forsendelse_id                   bigint REFERENCES forsendelse (forsendelse_id) not null,
    tittel                           text,
    ettersendelse_for_journalpost_id text,
    innsendings_id                   text,
    innsendingsfrist_dager           numeric,
    skjema_id                        text,
    opprettet_tidspunkt              timestamp without time zone DEFAULT now()      NOT NULL
);

CREATE TABLE IF NOT EXISTS ettersendingsoppgave_vedlegg
(
    id                      bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    ettersendingsoppgave_id bigint REFERENCES ettersendingsoppgave (id) not null,
    tittel                  text,
    url                     text,
    skjema_id               text,
    opprettet_tidspunkt     timestamp without time zone DEFAULT now()   NOT NULL
);