name: Deploy feature
on:
  push:
    branches:
      - 'aa'
      - '!main'
      - '!dependabot/**'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    uses: navikt/bidrag-workflow/.github/workflows/pr.yaml@main
    secrets: inherit

  run-tests-for-opprett-oppgave-feature:
    runs-on: ubuntu-latest
    name: "Run tests: opprett-forsendelse"
    needs: build-deploy

    env:
      INGRESS_DOKUMENT_FORSENDELSE: https://bidrag-dokument-forsendelse-feature.dev.intern.nav.no
      INGRESS_CUCUMBER: https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no

    steps:
      - run: |
          curl -H "Content-Type: application/json" -i \
                -H "Authorization: Basic ${{ secrets.BIDRAG_CUCUMBER_CLOUD_AUTH }}" \
               --request POST \
               --data '{"noContextPathForApps":["bidrag-dokument-forsendelse"],"ingressesForApps":[
                   "${{ env.INGRESS_DOKUMENT_FORSENDELSE }}@tag:bidrag-dokument-forsendelse"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)