name: Deploy feature
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'

jobs:
  build-deploy:
    name: "Build and deploy"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit