name: Deploy to prod
on:
  push:
    branches:
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    name: "Build and deploy to prod"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/release.yaml@main
    secrets: inherit

  tag:
    runs-on: ubuntu-latest
    name: Tag release
    permissions:
      contents: write
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Push latest image tag as github tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.deploy.outputs.tag }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}